name: SuperQA GitHub Action Integration Test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
 superqa-integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run SuperQA test plan
        uses: SuperQA-ai/superqa-githubaction@main
        env:
          SUPERQA_PARALLEL_RUN: 'true'
          SUPERQA_SKIP_NOTIFICATIONS: 'true'
        with:
          api_key: ${{ secrets.SUPERQA_API_KEY }}
          project_name: 'APM kingstrack'
          test_plan_name: 'superqagithubactiontesting'
          environment_name: 'production'
          base_url: 'https://app.superqa.ai'
